### ISSUE TITLE
fastify-oas-3.0.8 package not working when fastify upgraded to 4.x.x

### ISSUE THREAD

**Issue by nilesh2907** [SkeLLLa/fasify-oas#104]
when I upgrade my app to fastify 4.28.1 it throws "code":"FST_ERR_PLUGIN_VERSION_MISMATCH","name":"FastifyError","statusCode":500,"message":"fastify-plugin: fastify-static - expected '3.x' fastify version, '4.28.1' is installed"

**Comment by SkeLLLa** [comment]
That's expected. This plugin is only for versions <4. In version 4 openapi support has landed in "official" fastify-swagger plugin.
